/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Account_Information extends javax.swing.JFrame {

    /**
     * Creates new form Account_Information
     */
    private String cus_id_str;
    private int acc_no;
    public Account_Information(String cus_id_str) {
        initComponents();
        this.cus_id_str = cus_id_str;
        String sql = "SELECT * FROM Accounts WHERE Customer_id = '" +cus_id_str+"' ";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=4NF_test;user=sa;password=sa;encrypt=true;trustServerCertificate=true");

            // Use prepared statement to avoid SQL injection
            PreparedStatement pst = conn.prepareStatement(sql);
            
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String customer_id = rs.getString("customer_id");
                BigDecimal balance = rs.getBigDecimal("balance");
                int acc_no_get = rs.getInt("Account_No");
                
                this.acc_no = acc_no_get;
                txtBalance.setText(balance.toString());
                txtBalance.setEditable(false);

                txtAccNo.setEditable(false);
                txtAccNo.setText(String.valueOf(acc_no_get));

                txtCustomer_id.setText(this.cus_id_str);
                txtCustomer_id.setEditable(false);

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    //overload
    public Account_Information(int accno) {
        initComponents();
 
        String sql = "SELECT * FROM Accounts WHERE Account_No = '" +accno+"' ";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=4NF_test;user=sa;password=sa;encrypt=true;trustServerCertificate=true");

            // Use prepared statement to avoid SQL injection
            PreparedStatement pst = conn.prepareStatement(sql);
            
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String customer_id = rs.getString("customer_id");
                BigDecimal balance = rs.getBigDecimal("balance");
                int acc_no_get = rs.getInt("Account_No");
                
                this.cus_id_str = customer_id;
                this.acc_no = acc_no_get;
                txtBalance.setText(balance.toString());
                txtBalance.setEditable(false);

                txtAccNo.setEditable(false);
                txtAccNo.setText(String.valueOf(acc_no_get));

                txtCustomer_id.setText(customer_id);
                txtCustomer_id.setEditable(false);

            }

        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBackToMain = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        CheckSavingAcc = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCustomer_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("ACCOUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        btnBackToMain.setText("Back to home screen");
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 160, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Current Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Account number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        getContentPane().add(txtAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 170, 40));
        getContentPane().add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 170, 40));

        CheckSavingAcc.setText("Check saving accounts");
        CheckSavingAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSavingAccActionPerformed(evt);
            }
        });
        getContentPane().add(CheckSavingAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 160, 40));

        jButton4.setText("Create saving accounts");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 160, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("CustomerID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));
        getContentPane().add(txtCustomer_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 170, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed
        setVisible(false);
        MainPage main = new MainPage(cus_id_str);
        main.setVisible(true);
        main.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_btnBackToMainActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        CreateSaving create = new CreateSaving(acc_no);
        create.setVisible(true);
        create.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CheckSavingAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSavingAccActionPerformed
        try {
            var check = new CheckSaving(acc_no);
            check.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Account_Information.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CheckSavingAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckSavingAcc;
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCustomer_id;
    // End of variables declaration//GEN-END:variables
}
