/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banking;

import java.awt.HeadlessException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */

    public class Transaction extends javax.swing.JFrame {
        
        private int cus_id;
        private int my_acc_no;
        private BigDecimal my_balance;
      
        private String cus_id_str;
      
        
        public Transaction(String cus_id_str) {
            initComponents();
            this.cus_id_str = cus_id_str;
            this.cus_id = Integer.parseInt(cus_id_str);
            String sql = "SELECT Account_No, balance FROM Accounts WHERE customer_id= ? ";
            
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=4NF_test;user=sa;password=sa;encrypt=true;trustServerCertificate=true");
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, cus_id);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                // Assuming Account_No is a String and balance is a BigDecimal
            int accountNo = rs.getInt("Account_No");
            BigDecimal balance = rs.getBigDecimal("balance");

            // Now set the values to your class variables
            my_acc_no = accountNo;
            my_balance = balance;
            
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            dispose();
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOtherAcc_No = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAmountSelected = new javax.swing.JTextField();
        btnTransit = new javax.swing.JButton();
        btnBackToMain = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setSize(200,100);
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Transaction");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel5.setText("Amount:");

        txtOtherAcc_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherAcc_NoActionPerformed(evt);
            }
        });

        jLabel6.setText("To Account Number:");

        txtAmountSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountSelectedActionPerformed(evt);
            }
        });

        btnTransit.setText("Transit");
        btnTransit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransitActionPerformed(evt);
            }
        });

        btnBackToMain.setText("Back to home screen");
        btnBackToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAmountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOtherAcc_No, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnTransit)
                        .addGap(55, 55, 55)
                        .addComponent(btnBackToMain)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtherAcc_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransit)
                    .addComponent(btnBackToMain))
                .addGap(246, 246, 246))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 750, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMainActionPerformed

        setVisible(false);
        MainPage main = new MainPage(cus_id_str);
        main.setVisible(true);
        main.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnBackToMainActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);
 
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtOtherAcc_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherAcc_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherAcc_NoActionPerformed

    private void txtAmountSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountSelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountSelectedActionPerformed
    
   
    private void btnTransitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransitActionPerformed
        String otherAccNoStr = txtOtherAcc_No.getText();
    int otherAccNo = Integer.parseInt(otherAccNoStr);
    BigDecimal amountSelected = new BigDecimal(txtAmountSelected.getText());

    String sql = "SELECT Account_No, balance FROM Accounts WHERE Account_No= ?";
    try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=4NF_test;user=sa;password=sa;encrypt=true;trustServerCertificate=true");
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, otherAccNo);  

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            // The other account exists, retrieve data
            BigDecimal otherBalance = rs.getBigDecimal("balance");
            if(my_acc_no == otherAccNo){
                JOptionPane.showMessageDialog(null, "Invalid Account");
                dispose();
                Transaction trans = new Transaction(cus_id_str);
                trans.setVisible(true);
                trans.setLocationRelativeTo(null);
            }
            
            
            // Validate if the balance is sufficient for the transaction
            else if (my_balance.compareTo(amountSelected) >= 0) {
                    // The other account exists and has sufficient balance for the transaction

                    // Update SQL for the other account (Recipient account was added)
                    String updateSql1 = "UPDATE Accounts SET balance = balance + ? WHERE Account_No = ?";
                    try (PreparedStatement updatePst1 = conn.prepareStatement(updateSql1)) {
                        updatePst1.setBigDecimal(1, amountSelected);
                        updatePst1.setInt(2, otherAccNo);
                        updatePst1.executeUpdate();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Failed to update balance in the database: " + e.getMessage());
                    }

                    // Update SQL for the current account (Transit account was subtracted)
                    String updateSql2 = "UPDATE Accounts SET balance = balance - ? WHERE Account_No = ?";
                    try (PreparedStatement updatePst2 = conn.prepareStatement(updateSql2)) {
                        updatePst2.setBigDecimal(1, amountSelected);
                        updatePst2.setInt(2, my_acc_no);
                        updatePst2.executeUpdate();
                    }
                    
                    
                    String insertSQL = "INSERT INTO [newest_transaction] (Amount,transaction_date,customer_id) VALUES (?,getdate() ,?)";
                    try (PreparedStatement insertPst = conn.prepareStatement(insertSQL, Statement.RETURN_GENERATED_KEYS)) {
                        insertPst.setBigDecimal(1, amountSelected);   
                        insertPst.setString(2, cus_id_str);
                        insertPst.executeUpdate();
                        // Retrieve the generated transaction_id
                       try (ResultSet generatedKeys = insertPst.getGeneratedKeys()) {
                            if (generatedKeys.next()) {
                                int transaction_id = generatedKeys.getInt(1);

                                // You can use the transaction_id as needed
                                System.out.println("Generated Transaction ID: " + transaction_id);
                            } else {
                                throw new SQLException("Failed to retrieve generated keys for TRANSACTION TABLE");
                            }
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, "Failed to insert transaction record: " + e.getMessage());
                    }
                    JOptionPane.showMessageDialog(null, "Transaction is completed.");
                    setVisible(false);
                    MainPage main = new MainPage(cus_id_str);
                    main.setVisible(true);
                    main.setLocationRelativeTo(null);
                }
        } else {
                JOptionPane.showMessageDialog(null, "Invalid Transaction");
                dispose();
                Transaction trans = new Transaction(cus_id_str);
                trans.setVisible(true);
                trans.setLocationRelativeTo(null);
        }

    } catch (HeadlessException | ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(null, e);
        
}
    }//GEN-LAST:event_btnTransitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMain;
    private javax.swing.JButton btnTransit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmountSelected;
    private javax.swing.JTextField txtOtherAcc_No;
    // End of variables declaration//GEN-END:variables
    }